name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: install deps
      run: sudo apt update && sudo apt install -y pkg-config libgtk-3-dev libappindicator3-dev

    - name: install catch2
      run: >
        git clone https://github.com/catchorg/Catch2.git &&
        cd Catch2 &&
        git checkout v2.x &&
        cmake -Bbuild -H. -DBUILD_TESTING=OFF &&
        sudo cmake --build build/ --target install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Unix Makefiles"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}}
      
